spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled:  true
cloud:
  aws:
    region:
      static:
      auto: false
    stack:
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point:
      uri:
